const types = {
    //ACCOUNT CONSTANTS//

    SET_INITIAL: 'SET_INITIAL',

    USER_STATE_RESET: 'USER_STATE_RESET',

    REGISTER: {
        REQUEST: 'REGISTER_REQUEST',
        SUCCEED: 'REGISTER_SUCCEED',
        FAILED: 'REGISTER_FAILED',
    },

    LOGIN: {
        REQUEST: 'LOGIN_REQUEST',
        SUCCEED: 'LOGIN_SUCCEED',
        FAILED: 'LOGIN_FAILED',
    },

    EDIT_PROFILE: {
        REQUEST: 'EDIT_PROFILE_REQUEST',
        SUCCEED: 'EDIT_PROFILE_SUCCEED',
        FAILED: 'EDIT_PROFILE_FAILED',
    },

    CHANGE_AVATAR: {
        REQUEST: 'CHANGE_AVATAR_REQUEST',
        SUCCEED: 'CHANGE_AVATAR_SUCCEED',
        FAILED: 'CHANGE_AVATAR_FAILED',
    },

    LOGOUT: {
        REQUEST: 'LOGOUT_REQUEST',
        SUCCEED: 'LOGOUT_SUCCEED',
        FAILED: 'LOGOUT_FAILED',
    }

}

export default types